### ISSUE TITLE
Eliminate the need to manually enter a server name in nginx config

### ISSUE THREAD

**Issue by cewing** [wilson0xb4/rayfindr-config#1]
You should be using [templates](http://docs.fabfile.org/en/1.10/api/contrib/files.html#fabric.contrib.files.upload_template) to prevent needing to manually edit any config files.  Template out variables that change between deploys and then fill in those values using os.environ or other approaches (`select_server`, etc).

**Comment by cewing** [comment]
attn: @wilson0xb4

**Comment by wilson0xb4** [comment]
Now uses a template, thanks for pointing out the upload_template().
